### PR TITLE
Added useNativeDriver to Animated to supress warnings on RN .62

### PR DESCRIPTION
**Pull request by ricbermo**

### CODE REVIEW

**Comment by codypearce** [comment]
@ricbermo Nice, works great

**Comment by JakeHadley** [comment]
I did get one warning from `useNativeDriver` when I clicked into the textfield: 
```
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
    in TextFieldUnderline (at withTheme.js:11)
    in Context.Consumer (at withTheme.js:9)
    in _class (at TextFieldFlat.js:215)
    in TextFieldFlat (at withTheme.js:11)
    in Context.Consumer (at withTheme.js:9)
    in _class (at TextField.js:64)
    in TextField (at withTheme.js:11)
    in Context.Consumer (at withTheme.js:9)
    in _class (at AuthForm.js:88)
    in AuthForm (at SignupScreen.js:12)
    in SignupScreen (at SceneView.tsx:98)
    in SceneView (at useDescriptors.tsx:125)
    in CardContainer (at CardStack.tsx:531)
    in CardStack (at StackView.tsx:420)
    in KeyboardManager (at StackView.tsx:418)
    in Context.Consumer (at StackView.tsx:416)
    in StackView (at createStackNavigator.tsx:67)
    in StackNavigator (at App.js:34)
    in Root (at App.js:62)
    in App (at renderApplication.js:45)
```

**Comment by ricbermo** [comment]
@JakeHadley 
image
I haven't had a chance to test this myself but would you mind making sure you are using 0.27? As u can see on the screenshot both `Animated` have the expected `useNativeDriver` prop set.

**Comment by JakeHadley** [comment]
I'm installed off of master currently. Looks like this got merged into master, so I assume I have the latest.

**Comment by ricbermo** [comment]
@JakeHadley roger that, what about using `npm`?

**Comment by JakeHadley** [comment]
Not sure I understand. When I installed this morning I did `npm install <github repo path for master>`.

**Comment by ricbermo** [comment]
@JakeHadley that's fine. I was just asking if you could try installing the latest version from npm that was released this morning as well. I'm just asking because you may be using a cached version since the package.json from master maybe had `0.26`. I'm just speculating.

**Comment by JakeHadley** [comment]
Oh right. Yeah I can try.

**Comment by JakeHadley** [comment]
Just cleaned out `node_modules/material-bread`, removed from package.json, installed with `npm install material-bread`, re-ran, clicked into a basic `TextField`, same warning as before.

**Pull request merged**
