### PR TITLE
ListItem: Add State for onPress

### PR DESCRIPTION
**Pull request by alburdette619**
In #219 we fixed the animation ending automatically causing onPress to be called.  This was reverted to fix another but.  This is a compromise between the two issues.  Now, on a press, the animation should always end, and the full onPress should actually have to occur.

### CODE REVIEW

**Comment by codypearce** [comment]
@alburdette619 Getting some interesting behavior on the web: https://imgur.com/4Lp2sZC

**Comment by alburdette619** [comment]
@codypearce [this](https://github.com/codypearce/material-bread/pull/228#issuecomment-515744735) was introduced here but it doesn't seem to make much sense.  It is the difference in `onAnimationEnd` being an arrow function and it just being passed a function.  Do you want me to open another issue or fix it here?

**Comment by alburdette619** [comment]
@codypearce Fixed this issue.  It was just that the Storybook didn't have an onPress property so odds are it was already happening.

**Comment by codypearce** [comment]
@alburdette619 Looks good, thanks!

**Pull request merged**
