### PR TITLE
Android fab button issue

### PR DESCRIPTION
**Pull request by dann1609**
This PR fix fab button issues on android devices.

Currently android have issues where overflow elements are untouchables.

https://stackoverflow.com/questions/27010172/clipped-button-doesnt-receive-touch-input

This fix is only works for bottom tabbar.

### CODE REVIEW

**Comment by codypearce** [comment]
@dann1609 There's a failing test, can you update it?

**Comment by thyagarajarahul** [comment]
@dann1609 Have you solved the issue? Can you please guide me.

**Comment by codypearce** [comment]
@dann1609 I'm getting some issues with rendering the fab:

Android:
image


image

Web:

Components | AppbarBottom - Center Fab ⋅ Storybook 2019-09-07 23-56-19

**Comment by codypearce** [comment]
@dann1609 I was unable to push to your branch so I'm closing this in favor of #279 .

**Pull request closed without merging**
