### PR TITLE
TypeScript Definitions

### LINKED ISSUE #322: TypeScript Support
Is TypeScript currently supported? I may try to PR a typings file in the next few weeks if not.

This project is seriously awesome, thanks so much!

### PR DESCRIPTION
**Pull request by skubakdj**
Still a work in progress as a few definitions are missing (`BreadProvider`, `withTheme`, and probably a few others). Feedback welcome!

Closes #322.

### CODE REVIEW

**Comment by codypearce** [comment]
@skubakdj This looks great so far! 

@punisher97 I'd love your feedback on this PR if you have some time

**Comment by punisher97** [comment]
@skubakdj Thank you!, @codypearce Ok, I'll try it today and I'll tell you

**Comment by punisher97** [comment]
@codypearce is a very good declaration file, to improve in the future, divide into several files and add defaultProps and comments (using the website), example [AppBar](https://material-bread.org/components/appbar/#props)

```js
export interface AppbarProps {
  color?: Color
  style?: StyleProp<any>
  theme?: Theme
  barType?: 'normal' | 'simple' | 'prominent' | 'dense' | 'prominent dense'
  backgroundImage?: React.ReactNode
  position?: string
  elevation?: number

  navigation?: string | React.ReactNode
  onNavigation?: (...args: any[]) => void

  title?: string
  titleStyles?: StyleProp<any>
  onTitle?: (...args: any[]) => void
  subtitle?: string
  subtitleStyles?: StyleProp<TextStyle>
  textContainerStyles?: StyleProp<TextStyle>

  actionItems?: React.ReactNode

  children?: React.ReactNode
}

export class Appbar extends React.Component<AppbarProps> {
  render(): React.ReactElement
}
```

to

Components/AppBar.d.ts

```js
export enum BarTypeEnum {
    REGULAR = 'regular',
    PROMINENT = 'prominent',
    DENSE = 'dense',
    PROMINENT_DENSE = 'prominent dense',
  }

  export interface IActionItem {
    name: string;
    onPress: (e: any) => void;
  }

  export interface AppBarProps {
    /**Each can be an object or node, renders on the right */
    actionsItems?: React.ReactNode | Array<IActionItem>;
    /**Type of appbar, other components change based on type:
     * @type {string}: regular, prominent, dense, prominent dense
     */
    barType?: BarTypeEnum;
    /**Renders image element as background*/
    backgroundImage?: Image;
    /** Component's background color */
    color?: string;
    /** Shadow on container appbar*/
    elevation?: number;
    /** OnPress for navigation IconButton if provided. */
    onNavigation?: (...args: any[]) => void;
    /** OnPress for title string if provided. */
    onTitle?:(...args: any[]) => void;
    /** Renders IconButton if string, or renders custom node on left of title */
    navigation?: React.ReactNode
    /** CSS position values applied to root appbar */
    position?: 'fixed' | 'relative' | 'absolute';
    /** Only displays on barType prominent, under the Title */
    subtitle?: string;
    /** Styles Subtitle */
    subtitleStyles?: StyleProp<ViewStyle>;
    /** Displays on the left after navigation. If string it follows guidelines */
    title?: string | React.ReactNode;
    /** Styles title if provided as string */
    titleStyles?: StyleProp<ViewStyle>;
    /** Styles root element */
    style?: StyleProp<ViewStyle>;
  }
  export class AppBar extends React.Component<AppBarProps, any> {
    public static defaultProps = {
      barType: BarTypeEnum.REGULAR,
      color: 'primary',
      elevation: 8,
      position: 'relative',
    };
    render(): React.ReactElement
  }
}
```
For me it's fine, I work with this, thanks!

**Comment by skubakdj** [comment]
Awesome suggestions @punisher97! Thanks for taking a look.

I should have some time this weekend to finish up the remaining definitions and give everything a final look over.

**Comment by skubakdj** [comment]
Just added the remaining types. I'm not sure `withTheme` is completely correct, but it seemed to work with some cursory testing.

It also seems like Travis is throwing `prettier` errors on files that haven't been modified. Not sure what's going on there but @codypearce if there's anything I need to change please let me know!

**Comment by codypearce** [comment]
@skubakdj Looks great! Thanks for your contribution! I moved the `index.d.ts` to src so it will be served along with the project entry point `index.js`

**Comment by punisher97** [comment]
> @skubakdj Looks great! Thanks for your contribution! I moved the `index.d.ts` to src so it will be served along with the project entry point `index.js`

@codypearce  Sorry remember add [types key](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) in package.json to working properly;

**Pull request merged**
